sudo: true
language: node_js
node_js:
  '8'
addons:
  chrome: stable
script:
  yarn test:cov
  google-chrome --pack-extension=./dist || true
#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#    secure: QC7/o2q6KIKpfdDCG7B59loTE/PJTI9PE/mlwwIG/Wwlx69lFbeuNGBelD8kEo2Cc9c5PfIyMxGt622VWyq372hO1q7itYwidF/s3p4Xan17vYmoz6u21DFaL88TPW1Nly+mJo1aTzcBzG83qHDL62V+F6Ao4hjZZkrSwfSRbIg2mDVBh62L6VDjwbKKxDSCMSmttkFY00mq7DCvjhbvvmPql0AQZgRkZeFYtq+DXMHHkOz+m3XOad7d+hOw3+BnoipDZSG4eCkxSfUpUA5fdi1Cq8ZyaGnSjWy3fG1S93WAb4Btq610LV9X6yRJl3uNkB8jljb6BHah9ZZ7oODdXdV+NOJepjYMpwuJHTl9x3s87fqDE4HCHqKeCwHxQwtjgVxSC/wWw74ao56/zzNuf5nixRWeEUHcdkBGKGa0cpc+1Y/TgRctC6tgQUl9EUVPlPOwX1x9Osp08cSjC3oVzuxeSPcuHmGQl7HYTx8OlbOUMaoFZDlUPPsAqO6oUZDPESjeuq8kVnu/PNTYZJtILYp0ecHiAyWL87nwYxE/BL6vsT7FzeFaFA42wi+MFFBXkCMj8nb9hBmfJ26wB9rnVxEzhTJHgDDifE9kTe8oNNdQCE3tHiaqmvzT9D9sZoFZiR02ljDBNguopYDnOr5eAgV+Tnj7aXh7XDv5PfC0FCg=
#  file: dist.crx
#  on:
#    repo: kanekotic/Gtimecarder